import messageModel from "../models/messageModel.js";
import { sendEmail } from "../config/emailService.js";

// Create new message
export const createMessage = async (req, res) => {
  const { name, phone, email, message } = req.body;

  // Validate required fields
  if (!name || !phone || !message) {
    return res.status(400).json({ 
      error: "Please provide name, phone number, and message. These fields are required." 
    });
  }

  try {
    // Create and save message to database
    const newMessage = await messageModel.create({
      name: name.trim(),
      phone: phone.trim(),
      email: email ? email.trim() : undefined,
      message: message.trim(),
    });

    // Send email notification if email is provided
    if (email && email.trim()) {
      try {
        const emailSubject = `🔔 New Contact Inquiry from ${name} - TechCulture AI`;
        const emailHtml = `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9;">
            <div style="background-color: #ffffff; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
              <div style="text-align: center; margin-bottom: 30px;">
                <h2 style="color: #2563eb; margin: 0; font-size: 24px;">📨 New Contact Inquiry</h2>
                <p style="color: #64748b; margin: 5px 0 0 0;">TechCulture AI - Contact Form Submission</p>
              </div>
              
              <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
                <h3 style="color: #334155; margin-top: 0; font-size: 18px;">Contact Details</h3>
                <table style="width: 100%; border-collapse: collapse;">
                  <tr>
                    <td style="padding: 8px 0; color: #64748b; font-weight: 600; width: 100px;">Name:</td>
                    <td style="padding: 8px 0; color: #1e293b;">${name}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; color: #64748b; font-weight: 600;">Phone:</td>
                    <td style="padding: 8px 0; color: #1e293b;">${phone}</td>
                  </tr>
                  <tr>
                    <td style="padding: 8px 0; color: #64748b; font-weight: 600;">Email:</td>
                    <td style="padding: 8px 0; color: #1e293b;"><a href="mailto:${email}" style="color: #2563eb; text-decoration: none;">${email}</a></td>
                  </tr>
                </table>
              </div>
              
              <div style="background-color: #f0f9ff; padding: 20px; border-radius: 8px; border-left: 4px solid #2563eb;">
                <h3 style="color: #334155; margin-top: 0; font-size: 18px;">💬 Message</h3>
                <p style="color: #1e293b; line-height: 1.6; margin: 0;">${message.replace(/\n/g, '<br>')}</p>
              </div>
              
              <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center;">
                <p style="color: #64748b; font-size: 14px; margin: 0;">
                  📅 Received on: ${new Date().toLocaleString('en-US', { 
                    timeZone: 'Asia/Kolkata',
                    year: 'numeric',
                    month: 'long', 
                    day: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit',
                    hour12: true
                  })}
                </p>
                <p style="color: #94a3b8; font-size: 12px; margin: 10px 0 0 0;">
                  This email was automatically generated by TechCulture AI contact system.
                </p>
              </div>
            </div>
          </div>
        `;

        await sendEmail({
          sendTo: "marketing@techculture.ai",
          subject: emailSubject,
          html: emailHtml,
        });
      } catch (emailError) {
        // Silently handle email errors without logging
      }
    }

    res.status(201).json({
      success: true,
      message: "Message sent successfully",
      data: newMessage
    });

  } catch (error) {
    res.status(500).json({
      success: false,
      error: "Failed to send message. Please try again."
    });
  }
};

// Get all messages
export const getAllMessages = async (req, res) => {
  try {
    const messages = await messageModel
      .find()
      .sort({ createdAt: -1 });

    res.status(200).json({
      success: true,
      data: messages
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: "Failed to fetch messages"
    });
  }
};